### ISSUE TITLE
Releases tab seems to be a bit messed up

### ISSUE THREAD

**Issue by BradPatras** [tus/TUSKit#183]
The [releases tab](https://github.com/tus/TUSKit/releases) looks a bit neglected, there's no release for 3.2.1, there seems to be a duplicate release (3.2 vs 3.2.0) and 3.2.0 from last summer is still marked as the latest release, instead of 3.3.  

I'm not super familiar with versioning norms but it seems kinda weird that versions went from X.X.X to just X.X for the past two releases but maybe that's fine.

Tagging @donnywals since they seem to be the one responsible for releases.

**Comment by donnywals** [comment]
Hey Brad! 

Very strange that GH reverted back to listing 3.2.0 as the latest release for the repo. I did mark 3.3 as the latest when I released it yesterday.

Either way, that's fixed now. And so is the duplicate 3.2.0.

I've also relabeled the released to have a trailing .0 again since that's what the repo historically has. I won't fix the tags because going forward I'll make tags match the x.x.x format too. Again because that's how the repo has historically done it and I think it's fair that you're calling this out even when x.x still follows semver so any dependency managers should be totally fine with x.x for normal dot releases and x.x.x for patch releases.

Anyway, thanks for mentioning this and I'll make sure to keep a close eye on the release tab going forward.
