### ISSUE TITLE
 is it available for swift 4 version?

### ISSUE THREAD

**Issue by fadielse** [tus/TUSKit#37]
Hi!
I used to use this library on my objective c project and i like it
is it available for swift version?
if not how to use this library on swift project?

thanks

**Comment by MMasterson** [comment]
Hey @fadielse,

There is no 100% `Swift` version in order to keep compatibility between `Objective-C` and `Swift`. But `Objective-C` is compatible  with `Swift`. If you import the `TUSKit` Library with a bridging header you will be able to use. Installing the Cocoapod Xcode should create one for you.

**Comment by MMasterson** [comment]
@fadielse 

I have added a `Swift` Example in the development branch.

**Comment by fadielse** [comment]
Hallo @MMasterson 

thank you for the example already given, I was greatly helped
